kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: vsphere-csi-attacher
  namespace: kube-system
spec:
  serviceName: vsphere-csi-attacher
  replicas: 1
  selector:
    matchLabels:
      app: vsphere-csi-attacher
  template:
    metadata:
      labels:
        app: vsphere-csi-attacher
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vsphere-csi-controller
            topologyKey: kubernetes.io/hostname
      serviceAccountName: vsphere-csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.0
          args:
            - --v=5
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/csi/sockets/pluginproxy/vsphere.csi.vmware.com
            type: DirectoryOrCreate
