kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-fcd
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: vsphere.csi.vmware.com
parameters:
  parent_type: "ONLY_ACCEPTABLE_VALUES_ARE: DatastoreCluster OR Datastore"
  parent_name: "REPLACE_WITH_YOUR_DATATORECLUSTER_OR_DATASTORE_NAME"
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - IF_USING_ZONES_REPLACE_WITH_ZONE_VALUE
  - key: failure-domain.beta.kubernetes.io/region
    values:
    - IF_USING_ZONES_REPLACE_WITH_REGION_VALUE
